Color enhance
highperformancecoder/scidavis-old pull request #104
Opened 2018-10-09 20:29 UTC by gbm19

This PR systematizes the use of ColorButton to define all colors in graphics.
It also allows to choose an alpha value (transparency/opacity) for each color.
Color values (including alpha) are stored in .sciproj files as #AARRGGBB.
Thus, files saved with this version can not be properly read with previous SciDAVis versions that stored colors as #RRGGBB.
It should solve github issue #64, and sf #278.

2018-10-09 23:09 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	}
The magic numbers 8 and 3 bother me a bit. I assume that maybe the dialog is perhaps 8x3 or something? At very least, there should be a static_assert that 8*3 <= colors_count.

Also what happens to standard colours 3,4,5, 9,10,11, ...?

2018-10-09 23:15 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +}
Kind of a nice hack, but what happens when someone wants a very translucent shade of black?

2018-10-09 23:23 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	return (ite->isValid());
Dereferencing the end of a sequence (as what happens if the colour is not found) has undefined behaviour, and could even cause a null dereference crash.

The return test could be as simple as ite-color < colors_count, or to be more std libraryish ite!=std::end(colors)

2018-10-09 23:25 UTC, highperformancecoder commented on libscidavis/src/ColorButton.h
> +
inline function rather than macro here

2018-10-09 23:27 UTC, highperformancecoder commented on libscidavis/src/ColorButton.h
> +	static int numPredefinedColors();
This is egregious encapsulation. colors_count is already a perfectly good constant public attribute.

2018-10-09 23:33 UTC, highperformancecoder commented on libscidavis/src/PlotDialog.cpp
> +	QColor color = c;
Why not rename the argument color?

2018-10-09 23:34 UTC, highperformancecoder commented on libscidavis/src/PlotDialog.cpp
> +	QColor color = c;
If color needs to be mutable, which is the likely reason, why not make the argument a QColor, and pass by value?

2018-10-09 23:35 UTC, highperformancecoder commented on libscidavis/src/PlotDialog.cpp
> +	if (c.alpha() != boxBackgroundTransparency->value())
ditto

2018-10-09 23:38 UTC, highperformancecoder requested changes
As per code review comments, there a few niggles to pick.

2018-10-10 17:01 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +	}
QColorDialog has 48 basic colors in a 6x8 grid. 
Using: 
 `for (int i=0; i < colors_count; i++) {QColorDialog::setStandardColor(i, colors[i].rgb());};`
arranges the colors in columns of 6. I  prefer to arrange them in rows of 8 colors each

2018-10-10 17:08 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +}
I have my doubts that there is someone able to distinguish that color #00000030 from white.
If someone complains, we will have to store colors with two variables (type and value).
Now, with very little effort we cover almost all #aarrggbb range.

2018-10-10 17:10 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +}
"... that color `#30` from white. "  
should be
"... that color (`#00000030`) from white."

2018-10-10 17:18 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +	return (ite->isValid());
Qt takes care of all that trouble.

2018-10-10 17:25 UTC, gbm19 commented on libscidavis/src/ColorButton.h
> +
Ok. See forthcoming commits.
My first intention was to require Qt5 to use only `QColor::HexArgb`. 
But I find it useful to have the color ehancement also for Qt4.

2018-10-10 17:28 UTC, gbm19 commented on libscidavis/src/ColorButton.h
> +	static int numPredefinedColors();
Ok. I agree that `numPredefinedColors` can easily be removed.
I simply took needed code over from ColorBox.{h,cpp}.

2018-10-10 21:21 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	}
Maybe a comment along the lines of rearranging the stand ard layout of standard colours might be useful. It puzzled me why you were only allocating half the colours.

The static_assert might also be useful, in case someone decides to remove some from the list, or monkey around with the magic numbers.

2018-10-10 21:41 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +}
#00000030 should be transparent actually. Mentally, I had the alpha channel trailing the colour channels, but with the # codes, its conventionally listed first.

However, the Qt documentation does not say how the 4 bytes are packed in an unsigned int. So does 0x30 mean #00000030 (transparent) or #30000000 (a very translucent shade of black)? It may depend on the machine endianess.

In principle, all shades of transparent are equivalent, and so that gives a wide range of codes to map to your standard colour table, but I'd think I'd shy away from mapping 0 (which is the obvious choice to represent transparent) to solid black, which is what you're currently doing.

2018-10-10 21:49 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	return (ite->isValid());
I don't think so. std::find returns an iterator pointing to the end of the sequence, which in this case will be a pointer to one past the end the colour array. ite->isValid() is completely undefined - the compiler could initialise the memory past the end of the array to zero, or some garbage pattern, or it may put a properly initialised default QColor, or it may remain uninitialised to sone random value.

2018-10-10 21:52 UTC, highperformancecoder commented on libscidavis/src/ColorButton.h
> +
I'm sure you've read Stroustrup on macros. Whilst he may egg the pudding a bit, it is widely accepted that macros should be avoided where alternatives exist. In this case an inline string function implementation of COLORNAME will do the job.

2018-10-10 21:55 UTC, highperformancecoder commented on libscidavis/src/ColorButton.h
> +
Ah OK - you fixed this.

2018-10-10 22:05 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	// arranges the colors in columns of 6. Instead arrange them in rows of 8 colors each.
Your comment is still slightly confusing - given a 6x8 grid, columns of 6 is the same thing as rows of 8.
You could simply say "transpose the 6x8 grid", which is what you're actually doing.

2018-10-10 22:09 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	}
I'm still keen on the static_assert:

static_assert(8*6 <= colours_count, "not enough defaults colors");

Better still, name the 8 and the 6, and use the names both in the loop and the assert. That way, as soon as anyone touches this in an invalid way, it will thow up a compiler error.

2018-10-10 22:26 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +	return (ite->isValid());
I guess Qt appends a properly initialised QColor(Invalid) at end of array at the constructor, because that is what I get when I test the code.

2018-10-10 22:32 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +}
Qt docs  say explicitly "An ARGB quadruplet on the format #AARRGGBB, equivalent to an unsigned int." [http://doc.qt.io/archives/qt-4.8/qcolor.html#QRgb-typedef](http://doc.qt.io/archives/qt-4.8/qcolor.html#QRgb-typedef)

2018-10-10 22:42 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +}
Yes - but it doesn't say how the individual bytes are packed into that unsigned it. My supposition is that it may depend on endianess - but I don't know...

2018-10-10 22:45 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +}
I would expect that if the most and least significant byte were zero, then you have a guaranteed 2^16 different integer values mapping to transparent by stashing the values in the middle two bytes. I would avoid using 0, as that should definitely be reserved for transparent, but potentially the other 2^16-1 values are up for grabs...

2018-10-10 22:47 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +	return (ite->isValid());
It's not Qt. It's your compiler. Someone else's compiler may do it differently. Next year, your compiler may do it differently. It is not good to rely on it.

2018-10-10 22:50 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +}
But the use of inline COLORNAME allows us to ignore the details of using an uint to represent color. We save/load the color by its name, not by its uint.

2018-10-10 23:11 UTC, highperformancecoder commented on libscidavis/src/ColorButton.cpp
> +}
I can't see the full code, so I'm missing your point. How is colorIndex to be used? At the moment, if I pass in QColor("#00000000") (ie transparent), colorIndex will return 0, (ie black). If colorIndex is private or protected, this may not matter much, of course, as perhaps there is no use case for passing transparent (or nearly transparent colours) to colorIndex. If it is a public method, then I think we do need to think how we deal with that possibility.

2018-10-11 20:51 UTC, gbm19 commented on libscidavis/src/ColorButton.cpp
> +}
QColor("#00000000") is as transparent as QColor("#00rrggbb") for any rgb value.
Thus, if you don't want to get 0 for colorIndex, use any value other than "#00000000"
Also, a transparent color is not very useful to represent data.
On the other hand, colorIndex() is only indispensable for the automatic color advance used when plotting several curves in the same graph.

2018-10-12 09:51 UTC, gbm19 commented
Notice that last commit modifies the format of saved settings file (SciDAVis.conf)

2018-10-12 23:15 UTC, highperformancecoder commented
Re SciDAVis.conf, is the software backwardly compatible with the previous .conf file?

2018-10-13 08:07 UTC, gbm19 commented
No. Code in this PR does not properly read  color values in previous version .conf file.
And code in [fc70ebc](https://github.com/highperformancecoder/scidavis/commit/fc70ebcf0a7b7511b762c44a09c44978b95d77ae) does not read .conf files written with this PR.
Until this PR there were 19 color values saved in SciDAVis.conf, 10 saved in "#rrggbb" format, and 9 saved in `QVariant` format. 
This PR stores all color values in "#aarrggbb" format.

2018-10-20 23:05 UTC, merged