Fix for bugs 383, 385.
highperformancecoder/scidavis-old pull request #125
Opened 2019-08-18 18:42 UTC by gbm19

2019-08-19 00:49 UTC, highperformancecoder requested changes
Please fix up  offset of 15 or 16 depending on tables being empty or not.

2019-08-19 00:49 UTC, highperformancecoder commented on libscidavis/src/ApplicationWindow.cpp
> +                          cl.lCapStyle = curve[15].toInt();
This code bothers me. It would seem that curve[15] is penWidth, unless app->renamedTables is empty. ISTM, that you need a paramOffset variable, which is set to 15 when renamedTables is empty, and 16 otherwise, then calulate the following series of indices relative to paramOffset.

Of course, better still is to have a struct that names the relevant parameter fields, but that would be a refactor too far at this point in time, I suspect.

Unless, of course, renamedTables is guaranteed to be empty if d_file_version>=0x0118000, in which case an assert of that fact would be required.

2019-08-19 00:49 UTC, highperformancecoder commented on libscidavis/src/ApplicationWindow.cpp
> +                              colsList<<curve[2]; colsList<<curve[20+s_offset]; colsList<<curve[21+s_offset];
This solution is similar to what I was proposing for the previous problem...

2019-08-19 00:49 UTC, highperformancecoder commented on libscidavis/src/RangeSelectorTool.cpp
> +				if (qFuzzyCompare(curve->x((i + point) % n), max_x))
I looked at the docs for qFuzzyCompare, and it didn't tell me what tolerance is used. Normally, for these sort of purposes, I roll my own functions along the lines of:
bool near(double x, double y, double tol) {
  double r=abs(x)+abs(y);
  if (r==0) return true;
  else return abs(x-y) < tol * r;
}
(PS - I haven't thought about NANs or Infs here)

Anyway, given that qFuzzyCompare must be practically indistinguishable from ==, I'll pass this use here.

2019-08-19 12:20 UTC, gbm19 commented on libscidavis/src/ApplicationWindow.cpp
> +                          cl.lCapStyle = curve[15].toInt();
ISTM that renamedTables does not change how curve parameters have to be read.

2019-08-19 12:21 UTC, gbm19 commented on libscidavis/src/RangeSelectorTool.cpp
> +				if (qFuzzyCompare(curve->x((i + point) % n), max_x))
You can get the definition of qFuzzyCompare in:
/usr/include/Qt/qglobal.h:2145 (for Qt 4.8.7)
/usr/include/qt5/QtCore/qglobal.h:827 (for Qt 5.12.4)

2019-08-19 12:23 UTC, gbm19 commented on libscidavis/src/RangeSelectorTool.cpp
>  		// try to be intelligent about selecting the inactive point
Fix obtention of curve x-limits:
curve->minXValue(), curve->maxXValue() are obtained from curve->boundingRect() (see qwt_plot_curve.h in qwt source)
For curves with Symbols, curve->boundingRect() (see PlotCurve.cpp:345) is larger than curve->QwtPlotCurve::boundingRect() (see qwt_plot_curve.cpp:501)
Here we need to use the actual data limits, given by either curve->data().boundingRect() or curve->QwtPlotCurve::boundingRect()

2019-08-20 04:55 UTC, highperformancecoder commented on libscidavis/src/ApplicationWindow.cpp
> +                              colsList<<curve[2]; colsList<<curve[20+s_offset]; colsList<<curve[21+s_offset];
Looks good!

2019-08-20 05:00 UTC, merged

2019-08-20 05:05 UTC, highperformancecoder approved these changes

2019-08-20 05:05 UTC, highperformancecoder commented on libscidavis/src/RangeSelectorTool.cpp
> +				if (qFuzzyCompare(curve->x((i + point) % n), max_x))
Very similar to my near function, with a tolerance of 1e-12.