Add python support to cmake build
highperformancecoder/scidavis-old pull request #146
Opened 2020-07-12 17:23 UTC by gbm19

2020-07-12 21:05 UTC, ghost requested changes

2020-07-12 21:05 UTC, ghost commented on CMakeLists.txt
> +option( ENABLE_python "Enable Python binding" ON )
Isn't ENABLE_PYTHON better?
Binding or Scripting?

2020-07-12 21:05 UTC, ghost commented on cmake/scidavis-python.cmake
> +  find_package(PythonInterp 3)
According to cmake [documentation](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html?highlight=findpython#module:FindPythonInterp) this is a deprecated module, you should use FindPython3 instead.

2020-07-12 21:05 UTC, ghost commented on libscidavis/CMakeLists.txt
> +    )
How about Windows?

2020-07-12 21:05 UTC, ghost commented on cmake/scidavis-python.cmake
> +  set(scidavis_pyqt5_SRC
SCIDAVIS_PYQT5_SRCS

2020-07-13 05:21 UTC, highperformancecoder commented on cmake/scidavis-python.cmake
> +  find_package(PythonInterp 3)
Makes sense

2020-07-13 05:31 UTC, highperformancecoder commented on cmake/scidavis-python.cmake
> +  set(scidavis_pyqt5_SRC
Could you justify why CMake variables should all be upper case? Seems like it is just a style thing, and often the choice is opposite (free-case).

2020-07-13 05:35 UTC, highperformancecoder commented on libscidavis/CMakeLists.txt
> +    )
Currenly Python is not supported on Windows because MXE (a Windows cross compiler running on Linux) doesn't support it. I'm working on that (PyQt is probably too large a bridge to cross with MXE, hence the Classdesc-based reflection approach of SciDaVis 3.x).

Nevertheless, if you want to get Python to work on Visual Studio builds, knock yourself out!

2020-07-13 06:15 UTC, ChinouneMehdi commented on cmake/scidavis-python.cmake
> +  set(scidavis_pyqt5_SRC
I don't have a strong argument, just a style coding convention that I saw in many projects.

2020-07-13 06:16 UTC, ChinouneMehdi commented on libscidavis/CMakeLists.txt
> +    )
So python support should be disabled on Windows.

2020-07-13 16:48 UTC, gbm19 commented on CMakeLists.txt
> +option( ENABLE_python "Enable Python binding" ON )
Actually both. Binding is the hard one to get it properly.

2020-07-13 16:48 UTC, gbm19 commented on cmake/scidavis-python.cmake
> +  find_package(PythonInterp 3)
See next commit

2020-07-13 16:49 UTC, gbm19 commented on cmake/scidavis-python.cmake
> +  set(scidavis_pyqt5_SRC
I just adapted the naming of PLplot.

2020-07-15 02:13 UTC, highperformancecoder commented on libscidavis/CMakeLists.txt
> +    )
Only on the MXE target. If you can get it to work on Visual Studio, you're welcome to enable it, but I for one, won't be supporting that configuration.

2020-07-15 02:14 UTC, highperformancecoder commented on cmake/scidavis-python.cmake
> +  set(scidavis_pyqt5_SRC
OK - let's leave it as is for now. I'm not a fan of overly prescriptive style guides.

2020-07-15 02:17 UTC, merged

2020-07-15 06:01 UTC, alxpl commented
Will cmake replace make or will they both be available?

2020-07-15 09:12 UTC, ChinouneMehdi commented
> Will cmake replace make or will they both be available?

You mean qmake.
Because cmake is just a generator. You can generate Makefile, Ninja-build, Visual studio project, Xcode project, ...etc.

2020-07-15 09:27 UTC, alxpl commented
On Wed, Jul 15, 2020, 11:12 مهدي شينون (Mehdi Chinoune) <
notifications@github.com> wrote:

> Will cmake replace make or will they both be available?
>
> You mean qmake.
> Because cmake is just a generator. You can generate Makefile, Ninja-build,
> Visual studio project, Xcode project, ...etc.
>

Yes, sorry, I wanted to write qmake, but at the moment I had just finished
working on a spec file with %make macros.
The thing is that as package maintainers (Fedora here) we are supposed to
stay close to upstream, so if everything is going to be built and tested
using cmake, I should switch as well.

2020-07-15 12:41 UTC, highperformancecoder commented
On Wed, Jul 15, 2020 at 02:27:40AM -0700, alxpl wrote:
> On Wed, Jul 15, 2020, 11:12 مهدي شينون (Mehdi Chinoune) <
> notifications@github.com> wrote:
> 
> > Will cmake replace make or will they both be available?
> >
> > You mean qmake.
> > Because cmake is just a generator. You can generate Makefile, Ninja-build,
> > Visual studio project, Xcode project, ...etc.
> >
> 
> Yes, sorry, I wanted to write qmake, but at the moment I had just finished
> working on a spec file with %make macros.
> The thing is that as package maintainers (Fedora here) we are supposed to
> stay close to upstream, so if everything is going to be built and tested
> using cmake, I should switch as well.
> 

That's the plan. There's still a bit to go porting over the relevant
options from qmake to cmake.


-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders     hpcoder@hpcoders.com.au
                      http://www.hpcoders.com.au
----------------------------------------------------------------------------