Remove boost dependency from liborigin
highperformancecoder/scidavis-old pull request #41
Opened 2017-06-21 22:15 UTC by gbm19

This PR provides the changes in liborigin and scidavis to remove boost (iequals, variant) from its build requires. The relevant changes in liborigin have been coded by Stefan Gerlach (liborigin, LabPlot).
I simply adapted them for use with scidavis.

2017-06-21 22:58 UTC, highperformancecoder approved these changes

2017-06-21 22:59 UTC, highperformancecoder approved these changes

2017-06-21 23:00 UTC, highperformancecoder approved these changes

2017-06-21 23:02 UTC, highperformancecoder commented on 3rdparty/liborigin/CMakeLists.txt
> -find_package(Boost REQUIRED)
Fine, but given we don't use cmake any more, this file can probably be removed in its entirety

2017-06-21 23:27 UTC, highperformancecoder requested changes

2017-06-21 23:27 UTC, highperformancecoder commented on 3rdparty/liborigin/OriginObj.h
> +	//		printf("~Variant()\n");
Leaving the destructor unimplemented will cause memory leaks whenever a string is stored in this type.

2017-06-21 23:27 UTC, highperformancecoder commented on 3rdparty/liborigin/OriginObj.h
> +				new(&as_string) string(v.as_string);
This can be replaced by assignment, and the destructor on line 223 removed.

2017-06-21 23:27 UTC, highperformancecoder commented on 3rdparty/liborigin/opj2dat.cpp
> +							outf << (value.as_string).c_str() << "; ";
c_str() is redundant here.

2017-06-21 23:27 UTC, highperformancecoder commented
Please fix the memory leak in the implementation of Origin::variant.

2017-06-21 23:37 UTC, gbm19 commented
Well, someday there will be a new liborigin release. Then it will be
treated like the other libs (e.g., muparser).
So I prefer to keep the CMakeList.txt, even though liborigin is so simple
now that you can  almost compile it by hand.
Also, I believe that Scidavis would benefit from switching to cmake instead
of qmake for compiling.

2017-06-22 1:02 GMT+02:00 Russell Standish <notifications@github.com>:

> *@highperformancecoder* commented on this pull request.
> ------------------------------
>
> In 3rdparty/liborigin/CMakeLists.txt
> <https://github.com/highperformancecoder/scidavis/pull/41#discussion_r123387077>
> :
>
> > @@ -4,10 +4,6 @@ cmake_minimum_required(VERSION 2.8)
>  # c++11 standard
>  add_compile_options(-std=c++11)
>
> -# boost library headers
> -find_package(Boost REQUIRED)
>
> Fine, but given we don't use cmake any more, this file can probably be
> removed in its entirety
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/highperformancecoder/scidavis/pull/41#pullrequestreview-45585525>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATTWvufnjdghbMur3fDz3C1I9yZt4nrKks5sGaEOgaJpZM4OBley>
> .
>

2017-06-22 00:14 UTC, highperformancecoder commented
If/when liborigin is restored as a standalone project, do you think this code is likely to make its way into that? Just wondering, because I was contemplating moving the liborigin code back into the scidavis codebase, and giving up on the pretense that it is a vendor branch.

Re qmake vs cmake, I personally think that both options are equally dreadful. But I do agree with (I think it was Dmitriy), that having chosen one system, we should stick with it consistently.

2017-06-22 23:09 UTC, highperformancecoder approved these changes

2017-06-22 23:14 UTC, highperformancecoder commented
The Travis failure looks unrelated - perhaps due to the recent upgrade of system images on Travis.

2017-06-22 23:14 UTC, merged